### ISSUE TITLE
`termsize::get()` returns (0, 0) when building for release

### ISSUE THREAD

**Issue by renpenguin** [softprops/termsize#19]
currently running arch linux with zsh as the shell, and finding this to be an issue in both the kitty terminal and vscode's built in terminal. the following program returns my actual terminal size when building with `cargo build` and (0, 0) when building with `cargo build --release`:
```rs
fn main() {
    println!("{:?}", termsize::get());
}
```

this issue is present on all versions of termsize, though only a few months ago this wasnt a problem

**Comment by 0x6b** [comment]
@redpenguinyt Although I'm not an owner of this repo, I want to put my two cents in. I have the same issue on macOS, and found that the following commit a.k.a. rust-lang/rust#120055 (stable as of [Rust 1.78](https://github.com/rust-lang/rust/releases/tag/1.78.0)) introduced this issue, using [cargo-bisect-rustc](https://rust-lang.github.io/cargo-bisect-rustc/).

- [Auto merge of #120055 - nikic:llvm-18, r=cuviper · rust-lang/rust@eaff1af](https://github.com/rust-lang/rust/commit/eaff1af8fdd18ee3eb05167b2836042b7d4315f6)

Since the change was significant (LLVM 17→18) I'm unsure how to proceed for any fix, but I found the following workarounds.

- Set `opt-level` to `0` or `1` for the release profile with [`Cargo.toml`](https://doc.rust-lang.org/cargo/reference/profiles.html) i.e.

  ```toml
  # Cargo.toml
  [profile.release]
  opt-level = 0 # or 1 will work. 2, 3, "s", "z" will introduce the issue.
  ```

- Pin Rust toolchain to 1.77.2 with the [toolchain file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) i.e.

  ```toml
  # rust-toolchain.toml
  [toolchain]
  channel = "1.77.2"
  ```

Hope this helps. Thanks!
